# Generated by Django 5.2.3 on 2025-07-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
