# Generated by Django 5.2.4 on 2025-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehicle_studentprogress_vehicleallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lessons_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Instructor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
